CREATE TABLE `payment_PaymentService` (
  `id` int NOT NULL AUTO_INCREMENT,
  `status` varchar(45) DEFAULT NULL,
  `transactionId` varchar(45) DEFAULT NULL,
  `transactionDate` varchar(45) DEFAULT NULL,
  `orderId` varchar(45) DEFAULT NULL,
  `paymentType` int DEFAULT NULL,
  `orderAmount` decimal(24,8) NOT NULL,
  `orderDetail` varchar(45) DEFAULT NULL,
  `UID` varchar(45) DEFAULT NULL,
  `paymentMode` varchar(250) DEFAULT NULL,
  `memberName` varchar(250) DEFAULT NULL,
  `memberEmail` varchar(45) DEFAULT NULL,
  `memberphone` varchar(45) DEFAULT NULL,
  `paymentCallbackByServiceURL` varchar(250) DEFAULT NULL,
  `expiredDtm` datetime DEFAULT NULL,
  `clientIP` varchar(255) DEFAULT NULL,
  `response_param` text,
  `currency` varchar(255) DEFAULT NULL,
  `createdDtm` datetime NOT NULL,
  `updatedDtm` datetime NOT NULL,
  `countryId` int DEFAULT NULL,
  `merchantBranchId` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`) USING BTREE,
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;